function ue = unitaryEvents( strobe, timePerBin, timePerRateWindow, timePerStep )
% function ue = unitaryEvents( strobe, timePerBin, timePerRateWindow, timePerStep )
   strobe = strobe signal, probably generated by strobesim
   timePerBin = width (in ms) of synchrony detection bin
   timePerRateWindow = width (in ms 

elementsPerBin = timePerBin / timePerStep;
elementsPerRateWindow = timePerRateWindow / timePerStep;

ue = [];

for n = elementsPerRateWindow:elementsPerBin:size(strobe,1)
    
    % calculate rates in Hz
    rate = sum( strobe(n-elementsPerRateWindow:n,:) ) ./ timePerRateWindow ./ 1000;
    
    